<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Coupon extends Model
{
    use HasFactory;

    protected $table ='coupons';
    protected $keyType ='string';
    public $incrementing = false;
    protected $primaryKey = 'coupon_id';

    protected $fillable =[
        'title',
        'expire_date',
        'type',
        'amount'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            $model->coupon_id = Str::uuid()->toString();
        });
    }
}
