<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class Coupon extends Model
{
    use HasFactory;

    protected $table ='coupons';
    protected $keyType ='string';
    public $incrementing = false;
    protected $primaryKey = 'coupon_id';

    protected $fillable =[
        'title',
        'category_name',
        'category_id',
        'expire_date',
        'amount_type',
        'type',
        'amount'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            $model->coupon_id = Str::uuid()->toString();
        });
    }
    public function category(){

        return $this->belongsTo(Category::class, 'category_id', 'category_id');

    }
//    public function isExpire(){
//        return Coupon::firstWhere('expire_date','>',Carbon::now());
//    }
    public function isExpire(){
        return $this->expiry_date->isPast();
    }
}
